# Base configs
baseurl: "http://127.0.0.1:4000"
#baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: ""

# UI configs
title: "A collection"
subtitle: ""
author: "Christian Massold"
header:
 title: "A collection"
 subtitle: "by Christian Massold"
footer:
 name: "Welcome on my portfolio"
 bio: "I'm glad that you're here. I use this website to have a public collection of my favorite pictures that I took in the past years."
# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "camera-retro", "text": ""}, {"tag": "FNumber", "icon": "dot-circle-o", "text": "F"}, {"tag": "ExposureTime", "icon": "clock-o", "text": ""}, {"tag": "ISOSpeedRatings", "icon": "info-circle", "text": "ISO"}]'
